### ISSUE TITLE
`npm run start` 项目启动报错

### ISSUE THREAD

**Issue by dkvirus** [worldsong/vue2-shop#1]
- 已经将 server 和 vue2-shop 中的 packages.json 都 install 完毕，并且 server 项目也连接数据库成功。

- 启动 vue2-shop 时 `npm run start` 报了以下错误，看意思是说 *.vue 文件有问题，可是 down 下来之后就没动过那些代码，不明白具体怎么回事。

```
 ERROR  Failed to compile with 7 errors                                                                                                                                                                                          10:07:46


 error  in ./src/views/Cart.vue

Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.pitch (D:\study\vue\vue2-shop\node_modules\extract-text-webpack-plugin\dist\loader.js:57:11)

 @ ./src/views/Cart.vue 2:2-385
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/views/Address.vue

Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.pitch (D:\study\vue\vue2-shop\node_modules\extract-text-webpack-plugin\dist\loader.js:57:11)

// .....
```

**Comment by worldsong** [comment]
不能重现你的问题！开发模式不需要配ExtractTextPlugin。如有疑问QQ一对一解惑！
